"""Pytest fixtures for GenomeInsight tests."""

import pytest
from pathlib import Path


@pytest.fixture
def sample_data_dir():
    """Return path to sample test data directory."""
    return Path(__file__).parent / "data"


@pytest.fixture
def sample_ancestrydna_content():
    """Sample AncestryDNA format content."""
    return """#AncestryDNA raw data download
#This file was generated by AncestryDNA
#Data was collected using AncestryDNA array version: V2.0
#rsid	chromosome	position	allele1	allele2
rs429358	19	45411941	T	T
rs7412	19	45412079	C	C
rs1801133	1	11856378	C	T
rs1801131	1	11854476	A	C
rs1799945	6	26091179	C	C
rs1800562	6	26093141	G	G
rs4680	22	19951271	G	A
rs1800497	11	113400106	C	C
rs1042713	5	148206473	G	G
rs12248560	10	96521657	C	C
"""


@pytest.fixture
def sample_23andme_content():
    """Sample 23andMe format content."""
    return """# This data file generated by 23andMe at: Thu Jan 01 00:00:00 2026
#
# This file contains raw genotype data, including data that is not used in 23andMe reports.
#
# rsid	chromosome	position	genotype
rs429358	19	45411941	TT
rs7412	19	45412079	CC
rs1801133	1	11856378	CT
rs1801131	1	11854476	AC
rs4680	22	19951271	GA
"""


@pytest.fixture
def sample_ancestrydna_file(tmp_path, sample_ancestrydna_content):
    """Create a temporary AncestryDNA file."""
    file_path = tmp_path / "test_ancestry.txt"
    file_path.write_text(sample_ancestrydna_content)
    return file_path


@pytest.fixture
def sample_23andme_file(tmp_path, sample_23andme_content):
    """Create a temporary 23andMe file."""
    file_path = tmp_path / "test_23andme.txt"
    file_path.write_text(sample_23andme_content)
    return file_path


# APOE genotype test cases
# rs429358 (C=risk) + rs7412 (T=risk) determine isoform
@pytest.fixture
def apoe_e3e3_content():
    """APOE ε3/ε3 (most common, baseline risk)."""
    return """#AncestryDNA raw data download
#rsid	chromosome	position	allele1	allele2
rs429358	19	45411941	T	T
rs7412	19	45412079	C	C
"""


@pytest.fixture
def apoe_e3e4_content():
    """APOE ε3/ε4 (elevated risk)."""
    return """#AncestryDNA raw data download
#rsid	chromosome	position	allele1	allele2
rs429358	19	45411941	T	C
rs7412	19	45412079	C	C
"""


@pytest.fixture
def apoe_e4e4_content():
    """APOE ε4/ε4 (high risk)."""
    return """#AncestryDNA raw data download
#rsid	chromosome	position	allele1	allele2
rs429358	19	45411941	C	C
rs7412	19	45412079	C	C
"""


@pytest.fixture
def apoe_e2e3_content():
    """APOE ε2/ε3 (potentially protective)."""
    return """#AncestryDNA raw data download
#rsid	chromosome	position	allele1	allele2
rs429358	19	45411941	T	T
rs7412	19	45412079	C	T
"""
