"""
AI-powered report generator.

Generates natural language reports from genetic analysis results.
"""

from __future__ import annotations

from enum import Enum
from typing import Optional

from genomeinsight.ai.client import LLMClient, get_client, LLMProvider
from genomeinsight.ai.prompts import SYSTEM_PROMPT, build_prompt
from genomeinsight.clinical.analyzer import AnalysisResult


class ReportStyle(Enum):
    """Report style options."""
    TECHNICAL = "technical"
    CONSUMER = "consumer"


class AIReportGenerator:
    """
    Generate AI-powered natural language reports from genetic analysis.
    
    Example:
        >>> from genomeinsight.ai import AIReportGenerator, get_client
        >>> client = get_client()  # Auto-detects from environment
        >>> generator = AIReportGenerator(client)
        >>> report = generator.generate(analysis_result)
        >>> print(report)
    """
    
    def __init__(self, client: Optional[LLMClient] = None):
        """
        Initialize the report generator.
        
        Args:
            client: LLM client to use (auto-detected if None)
        """
        self._client = client
    
    @property
    def client(self) -> LLMClient:
        """Get the LLM client, lazy-loading if needed."""
        if self._client is None:
            self._client = get_client()
        return self._client
    
    def generate(
        self,
        result: AnalysisResult,
        style: ReportStyle = ReportStyle.CONSUMER,
        max_tokens: int = 4096,
    ) -> str:
        """
        Generate a natural language report from analysis results.
        
        Args:
            result: AnalysisResult from clinical analyzer
            style: Report style (technical or consumer)
            max_tokens: Maximum tokens in response
            
        Returns:
            Generated report as markdown string
        """
        prompt = build_prompt(result, style=style.value)
        
        report = self.client.generate(
            prompt=prompt,
            system=SYSTEM_PROMPT,
            max_tokens=max_tokens,
        )
        
        # Add header and disclaimer
        header = self._build_header(result, style)
        disclaimer = self._build_disclaimer(style)
        
        return f"{header}\n\n{report}\n\n{disclaimer}"
    
    def generate_both(
        self,
        result: AnalysisResult,
        max_tokens: int = 4096,
    ) -> dict[str, str]:
        """
        Generate both technical and consumer reports.
        
        Args:
            result: AnalysisResult from clinical analyzer
            max_tokens: Maximum tokens per response
            
        Returns:
            Dict with 'technical' and 'consumer' keys
        """
        return {
            "technical": self.generate(result, ReportStyle.TECHNICAL, max_tokens),
            "consumer": self.generate(result, ReportStyle.CONSUMER, max_tokens),
        }
    
    def _build_header(self, result: AnalysisResult, style: ReportStyle) -> str:
        """Build report header."""
        provider_name = self.client.provider.value.title()
        style_name = "Technical" if style == ReportStyle.TECHNICAL else "Consumer"
        
        return f"""# 🧬 GenomeInsight AI Report

**Report Type:** {style_name}  
**Generated by:** {provider_name} AI  
**Source:** {result.source_file}  
**Variants Found:** {result.variants_found} of {result.variants_analyzed} analyzed

---"""
    
    def _build_disclaimer(self, style: ReportStyle) -> str:
        """Build appropriate disclaimer based on style."""
        if style == ReportStyle.TECHNICAL:
            return """---

## Disclaimer

This report is generated by AI and is intended for informational and research purposes only. 
It should not be used as the sole basis for clinical decision-making. All findings should be 
validated through clinical-grade testing and interpreted by qualified healthcare professionals. 
Genetic variants have variable penetrance and expressivity, and environmental factors play a 
significant role in health outcomes.

*Generated by GenomeInsight with AI assistance. All analysis performed locally - your data never leaves your computer.*"""
        else:
            return """---

## ⚠️ Important Disclaimer

**This report is for educational purposes only and is NOT medical advice.**

- 🏥 Always consult with your doctor before making health decisions
- 🧬 Genetics is just ONE piece of your health puzzle
- 🌍 Lifestyle, environment, and other factors matter too
- 📋 Consider speaking with a genetic counselor for significant findings
- 🔬 This analysis may not detect all genetic variations

*Your genetic data was analyzed 100% locally on your computer - it was never uploaded anywhere. 
Generated by GenomeInsight with AI assistance.*"""
